name: mood_diary
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^9.2.2 
  auto_size_text: ^3.0.0
  dio: ^5.7.0
  expandable_text: ^2.3.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  path_provider: ^2.1.1
  popover: ^0.3.1
  table_calendar: ^3.1.2
  talker_bloc_logger: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  tap_debouncer: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  scrollable_clean_calendar: ^1.5.0
  scrolling_years_calendar:
    git:
      url: https://github.com/vkurseApp/flutter_scrolling_calendar.git

  shared_preferences: ^2.3.2
  provider: ^6.1.2
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  hive_generator: ^2.0.1
  build_runner:


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-Bold.ttf

    - family:  MoodDiaryIcons
      fonts:
       - asset: assets/fonts/MoodDiaryIcons.ttf
