/// Flutter icons MoodDiaryIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoodDiaryIcons
///      fonts:
///       - asset: fonts/MoodDiaryIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MoodDiaryIcons {
  MoodDiaryIcons._();

  static const _kFontFam = 'MoodDiaryIcons';
  static const String? _kFontPkg = null;

  static const IconData closeIcon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diaryIcon =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statsIcon =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarIcon =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yearcalendar =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monthcalendar =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trashIcon =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
